# Generated by Django 3.2.4 on 2022-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.FileField(upload_to='video/%y'),
        ),
    ]
